/**
 * @module MarkdownGenerator
 * Builds RIPSTOP.md content from resolved guardrails configuration.
 */
// Copyright (c) 2026 Jon Verrier

import { IRipstopConfig } from '../config/schema';

/** Regex to read embedded config hash from a generated RIPSTOP.md header. */
export const RIPSTOP_CONFIG_HASH_PATTERN = /from config hash `([a-f0-9]{64})`/i;

export type RipstopMdFormat = 'markdown' | 'claude' | 'cursor' | 'codex' | 'q';

export interface IGenerateRipstopMdOptions {
  /** Ripstop package version string for footer. */
  packageVersion: string;
  /** ISO-8601 timestamp for header. */
  generatedAtIso: string;
  /** SHA-256 hex from {@link hashResolvedRipstopConfig}. */
  configHash: string;
  /** Output variant. */
  format: RipstopMdFormat;
}

/**
 * Extracts the config hash embedded in a generated RIPSTOP.md body.
 * @param markdown - File contents.
 * @returns Lowercase hex digest, or undefined if not found.
 */
export function extractEmbeddedConfigHash(markdown: string): string | undefined {
  const match = markdown.match(RIPSTOP_CONFIG_HASH_PATTERN);
  return match ? match[1].toLowerCase() : undefined;
}

/**
 * Generates full RIPSTOP.md document for the given format.
 * @param config - Resolved Ripstop configuration.
 * @param options - Generation metadata.
 * @returns Markdown text.
 */
export function generateRipstopMarkdown(config: IRipstopConfig, options: IGenerateRipstopMdOptions): string {
  const core = buildCoreMarkdown(config, options);
  switch (options.format) {
    case 'markdown':
      return core;
    case 'claude':
      return applyClaudeFormat(core);
    case 'cursor':
      return applyCursorFormat(core);
    case 'codex':
      return applyCodexFormat(core);
    case 'q':
      return applyAmazonQFormat(core);
    default:
      return core;
  }
}

function buildCoreMarkdown(config: IRipstopConfig, options: IGenerateRipstopMdOptions): string {
  const blocks = buildBlockingSection(config);
  const lines: string[] = [
    '# RIPSTOP — Active Guardrails',
    '',
    '> Auto-generated from `.guardrails.yaml`. Do not edit by hand —',
    `> regenerate via \`ripstop generate-md\`. Last generated: ${options.generatedAtIso}`,
    `> from config hash \`${options.configHash}\`.`,
    '',
    '## What this repo blocks',
    '',
    'The following actions will fail at commit, push, or rebase time:',
    '',
    ...blocks,
    '',
    '## What this repo expects of you',
    '',
    '- Read this file before making structural changes.',
    '- If you would touch a protected path, stop and ask the human first.',
    '- If a check fires, read the rule ID and the remediation hint — fix the underlying issue rather than bypassing.',
    '- If you genuinely need to bypass, use the trailer format specified for that rule and reference a ticket in the reason.',
    '- Do not disable, weaken, or modify `.guardrails.yaml` to make a check pass. That is a guardrail violation in itself.',
    '- Do not edit this file directly. It is regenerated from config.',
    '',
    ...buildSelfProtectionSection(options.format),
    '',
    '## What to do if you trip a guardrail',
    '',
    '1. Read the rule ID in the error output (e.g. `pii.email`).',
    '2. Read the remediation hint after the rule ID.',
    '3. Fix the underlying issue. Most rules are clear about what is wrong.',
    '4. If you believe the rule is firing incorrectly, do not bypass. Surface the false positive in your PR description so a human can decide whether to add an exemption.',
    '5. If a human has authorised a bypass, use the trailer format above. Bypasses are logged and reviewed.',
    '',
    '---',
    '',
    `*Generated by Ripstop v${options.packageVersion}. For questions, see \`docs/ripstop-consumer-playbook.md\` or contact the platform team.*`,
    ''
  ];
  return lines.join('\n');
}

function readMode(raw: unknown): string | undefined {
  if (raw && typeof raw === 'object' && 'mode' in raw) {
    const mode = (raw as { mode?: string }).mode;
    return typeof mode === 'string' ? mode : undefined;
  }
  return undefined;
}

function isActiveCheck(raw: unknown): boolean {
  const mode = readMode(raw);
  return mode !== 'off';
}

function buildBlockingSection(config: IRipstopConfig): string[] {
  const bullets: string[] = [];
  const checks = config.checks;

  const ordered = ['pii', 'path-guard', 'test-skip', 'dependency-guard', 'history-guard', 'ripstop-md-fresh', 'reflog-witness'] as const;
  for (const name of ordered) {
    const raw = checks[name];
    if (!raw || !isActiveCheck(raw)) {
      continue;
    }
    const block = describeCheck(name, raw, config);
    if (block.length > 0) {
      bullets.push(...block);
    }
  }

  const orderedNames: string[] = [...ordered];
  for (const [name, raw] of Object.entries(checks)) {
    if (orderedNames.includes(name)) {
      continue;
    }
    if (!isActiveCheck(raw)) {
      continue;
    }
    bullets.push(`- **${humaniseCheckName(name)}** (rule: \`${name}\`)`);
    bullets.push(`  Mode: \`${readMode(raw) ?? 'warn'}\`. See Ripstop docs for this check.`);
    bullets.push('');
  }

  if (bullets.length === 0) {
    bullets.push('- *(No checks are enabled beyond `off` in the current configuration.)*');
    bullets.push('');
  }

  return bullets;
}

function humaniseCheckName(name: string): string {
  return name.split('-').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
}

function describeCheck(name: string, raw: Record<string, unknown>, config: IRipstopConfig): string[] {
  const lines: string[] = [];
  const mode = readMode(raw) ?? 'warn';

  switch (name) {
    case 'pii': {
      const patterns = Array.isArray(raw.patterns)
        ? (raw.patterns as { name?: string }[]).map((p) => p.name).filter(Boolean)
        : ['email', 'uk-mobile'];
      const extra = Array.isArray(raw.extra_patterns)
        ? (raw.extra_patterns as { name?: string }[]).map((p) => p.name).filter(Boolean)
        : [];
      const names = [...patterns, ...extra];
      const exemptions = Array.isArray(raw.exemptions)
        ? (raw.exemptions as { path?: string }[]).map((ex) => ex.path).filter(Boolean)
        : [];
      lines.push(`- **PII patterns in source files** (rule: \`pii\`)`);
      lines.push(`  Patterns: ${names.join(', ')}`);
      if (exemptions.length > 0) {
        lines.push(`  Exempt paths: ${exemptions.map((p) => `\`${p}\``).join(', ')}`);
      }
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    case 'path-guard': {
      const paths = Array.isArray(raw.protected_paths) ? (raw.protected_paths as string[]) : [];
      const trailer = typeof raw.approval_trailer === 'string' ? raw.approval_trailer : 'CHANGE-APPROVED';
      lines.push('- **Modifications to protected paths without approval trailer** (rule: `path-guard`)');
      if (paths.length > 0) {
        lines.push(`  Protected: ${paths.map((p) => `\`${p}\``).join(', ')}`);
      }
      lines.push(`  Trailer to attest approval: \`${trailer}: <ticket>\``);
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    case 'test-skip': {
      const blocked = Array.isArray(raw.blocked_annotations) ? (raw.blocked_annotations as string[]) : [];
      lines.push('- **New test-skip annotations without ticket reference** (rule: `test-skip`)');
      if (blocked.length > 0) {
        lines.push(`  Blocked: ${blocked.map((b) => `\`${b}\``).join(', ')}`);
      }
      if (raw.require_ticket === true) {
        lines.push('  A ticket reference is required when skips are introduced.');
      }
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    case 'dependency-guard': {
      lines.push('- **New runtime dependencies without an ADR** (rule: `dependency-guard`)');
      lines.push('  Configure manifests and ADR paths in `.guardrails.yaml` for this check.');
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    case 'history-guard': {
      const branches = Array.isArray(raw.protected_branches) ? (raw.protected_branches as string[]) : [];
      const blockForce = raw.block_force_push !== false;
      const blockDelete = raw.block_branch_delete_on_remote !== false;
      const parts: string[] = [];
      if (blockForce) {
        parts.push('Force-pushes');
      }
      if (blockDelete) {
        parts.push('branch deletions');
      }
      parts.push('rebases of pushed commits');
      lines.push(`- **${parts.join(', ')}** on protected branches (rule: \`history-guard\`)`);
      if (branches.length > 0) {
        lines.push(`  Protected branches: ${branches.map((b) => `\`${b}\``).join(', ')}`);
      }
      appendHistoryOverride(lines, config);
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    case 'ripstop-md-fresh': {
      const outputPath = typeof raw.output_path === 'string' ? raw.output_path : 'RIPSTOP.md';
      lines.push('- **RIPSTOP.md out of date vs. configuration** (rule: `ripstop-md-fresh`)');
      lines.push(`  Tracked file: \`${outputPath}\`. Regenerate with \`ripstop generate-md\` after changing \`.guardrails.yaml\`.`);
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    case 'reflog-witness': {
      lines.push('- **Witness logging of guardrails configuration** (rule: `reflog-witness`)');
      lines.push('  Appends a hash of `.guardrails.yaml` (and full text when it changes) plus a hash of `RIPSTOP.md` to the witness log for forensic recovery.');
      lines.push(`  Mode: \`${mode}\`.`);
      lines.push('');
      break;
    }
    default:
      break;
  }

  return lines;
}

function buildSelfProtectionSection(format: RipstopMdFormat): string[] {
  if (format === 'cursor') {
    return [
      '## What you must not modify',
      '',
      'NEVER modify `.guardrails.yaml`, `.guardrails/`, or `RIPSTOP.md`.',
      'These files configure the guardrails themselves. If you need to change them, stop and ask the human.',
      'Do not attempt to bypass a failing guardrail check by editing config.',
      '',
      'The following files configure the guardrails themselves. Modifying them to disable, weaken, or work around a check is a guardrail violation in itself, and will be flagged in review.',
      '',
      '- `.guardrails.yaml` — guardrails configuration',
      '- `.guardrails/` — guardrails state, snapshots, and witness logs',
      '- `.guardrails/checks/` — local check implementations (if present)',
      '- `RIPSTOP.md` — auto-generated; edit `.guardrails.yaml` instead',
      '',
      'If you genuinely need to change one of these — onboarding a new check, tuning a pattern after a central library update, adjusting an exemption with platform-team approval — open the change as a **separate PR**. Do not modify these files in the same commit as the work that triggered a check.',
      '',
      'The commit that modifies guardrails configuration must carry the trailer:',
      '',
      '    CHANGE-APPROVED: <ticket-id> <reason>'
    ];
  }

  return [
    '## What you must not modify',
    '',
    'The following files configure the guardrails themselves. Modifying them to disable, weaken, or work around a check is a guardrail violation in itself, and will be flagged in review.',
    '',
    '- `.guardrails.yaml` — guardrails configuration',
    '- `.guardrails/` — guardrails state, snapshots, and witness logs',
    '- `.guardrails/checks/` — local check implementations (if present)',
    '- `RIPSTOP.md` — auto-generated; edit `.guardrails.yaml` instead',
    '',
    'If you genuinely need to change one of these — onboarding a new check, tuning a pattern after a central library update, adjusting an exemption with platform-team approval — open the change as a **separate PR**. Do not modify these files in the same commit as the work that triggered a check.',
    '',
    'The commit that modifies guardrails configuration must carry the trailer:',
    '',
    '    CHANGE-APPROVED: <ticket-id> <reason>'
  ];
}

function appendHistoryOverride(lines: string[], config: IRipstopConfig): void {
  const trailers = config.bypass?.rule_specific_trailers ?? {};
  const history = trailers['history-guard'] ?? trailers.history;
  if (typeof history === 'string' && history.length > 0) {
    lines.push(`  Override trailer: \`${history}: <reason>\``);
  }
}

function applyClaudeFormat(core: string): string {
  const header = [
    '## Claude Code — context',
    '',
    'Read `@docs/ripstop-consumer-playbook.md` for recovery, governance, and bypass policy.',
    '',
    '<ripstop_guardrails>',
    ''
  ].join('\n');
  const footer = [
    '',
    '</ripstop_guardrails>',
    ''
  ].join('\n');
  return `${header}${core}${footer}`;
}

function applyCursorFormat(core: string): string {
  const prefix = [
    '# Repo guardrails (Cursor)',
    '',
    'Do read the sections below before editing. Do not weaken `.guardrails.yaml` to silence checks.',
    '',
    '---',
    ''
  ].join('\n');
  return `${prefix}${rewriteHeadingsForCursor(core)}`;
}

function rewriteHeadingsForCursor(markdown: string): string {
  return markdown
    .replace(/^## What this repo blocks/m, '## BLOCKING — What this repo blocks')
    .replace(/^## What this repo expects of you/m, '## REQUIRED — What this repo expects of you')
    .replace(/^## What you must not modify/m, '## FORBIDDEN — What you must not modify')
    .replace(/^## What to do if you trip a guardrail/m, '## RECOVERY — What to do if you trip a guardrail');
}

function applyCodexFormat(core: string): string {
  const prefix = [
    '# Codex — repository guardrails',
    '',
    'Example: if `path-guard` fires, add `CHANGE-APPROVED: TICKET-123` to the commit message when a human approved the infra change.',
    '',
    '---',
    ''
  ].join('\n');
  return `${prefix}${core}`;
}

function applyAmazonQFormat(core: string): string {
  const prefix = [
    '# Amazon Q — include these guardrails',
    '',
    'Treat the following as hard requirements at commit time; this file is advisory but errors will block the workflow.',
    '',
    '---',
    ''
  ].join('\n');
  return `${prefix}${core}`;
}
